### ISSUE TITLE
Error:  Build failed for the package: lucem

### ISSUE THREAD

**Issue by vpuris** [xTrayambak/lucem#24]
When downloading using nimble install https://github.com/xTrayambak/lucem, it shows an error. Any fixes to this? 

![Image](https://github.com/user-attachments/assets/1e4ba1f4-690b-4f84-95a7-fd88bcacc6c1)

**Comment by AshtakaOOf** [comment]
What is your distro?
on Fedora this should be fixed by doing
- `sudo dnf install libcurl-devel libXcursor-devel pkgconf-pkg-config`

**Comment by vpuris** [comment]
im on nobara which is based off of fedora, and sadly it didnt fix :d

**Comment by AshtakaOOf** [comment]
Each time I see nimble gcc errors it's on Fedora and it's always a different package 😭.
Can you send the log in its entirety here?

**Comment by vpuris** [comment]
nimble install
  Verifying dependencies for lucem@2.1.2
     Info:  Dependency on colored_logger@>= 0.1.0 already satisfied
  Verifying dependencies for colored_logger@0.1.0
     Info:  Dependency on jsony@>= 1.1.5 already satisfied
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on toml_serialization@>= 0.2.12 already satisfied
  Verifying dependencies for toml_serialization@0.2.14
     Info:  Dependency on serialization@any version already satisfied
  Verifying dependencies for serialization@0.2.6
     Info:  Dependency on faststreams@any version already satisfied
  Verifying dependencies for faststreams@0.3.0
     Info:  Dependency on stew@any version already satisfied
  Verifying dependencies for stew@0.2.0
     Info:  Dependency on results@any version already satisfied
  Verifying dependencies for results@0.5.1
     Info:  Dependency on unittest2@any version already satisfied
  Verifying dependencies for unittest2@0.2.3
     Info:  Dependency on unittest2@any version already satisfied
  Verifying dependencies for unittest2@0.2.3
     Info:  Dependency on unittest2@any version already satisfied
  Verifying dependencies for unittest2@0.2.3
     Info:  Dependency on stew@any version already satisfied
  Verifying dependencies for stew@0.2.0
     Info:  Dependency on results@any version already satisfied
  Verifying dependencies for results@0.5.1
     Info:  Dependency on unittest2@any version already satisfied
  Verifying dependencies for unittest2@0.2.3
     Info:  Dependency on stew@any version already satisfied
  Verifying dependencies for stew@0.2.0
     Info:  Dependency on results@any version already satisfied
  Verifying dependencies for results@0.5.1
     Info:  Dependency on unittest2@any version already satisfied
  Verifying dependencies for unittest2@0.2.3
     Info:  Dependency on pretty@>= 0.1.0 already satisfied
  Verifying dependencies for pretty@0.2.0
     Info:  Dependency on owlkettle@>= 3.0.0 already satisfied
  Verifying dependencies for owlkettle@3.0.0
     Info:  Dependency on nimgl@>= 1.3.2 already satisfied
  Verifying dependencies for nimgl@1.3.2
     Info:  Dependency on netty@>= 0.2.1 already satisfied
  Verifying dependencies for netty@0.2.1
     Info:  Dependency on flatty@>= 0.2.1 already satisfied
  Verifying dependencies for flatty@0.3.4
     Info:  Dependency on curly@>= 1.1.1 already satisfied
  Verifying dependencies for curly@1.1.1
     Info:  Dependency on libcurl@>= 1.0.0 already satisfied
  Verifying dependencies for libcurl@1.0.0
     Info:  Dependency on zippy@>= 0.10.6 already satisfied
  Verifying dependencies for zippy@0.10.16
     Info:  Dependency on webby@>= 0.1.7 already satisfied
  Verifying dependencies for webby@0.2.1
     Info:  Dependency on nanovg@>= 0.4.0 already satisfied
  Verifying dependencies for nanovg@0.4.0
     Info:  Dependency on siwin@#9ce9aa3efa84f55bbf3d29ef0517b2411d08a357 already satisfied
  Verifying dependencies for siwin@0.9.1
     Info:  Dependency on chroma@>= 0.2.6 already satisfied
  Verifying dependencies for chroma@0.2.7
     Info:  Dependency on vmath@>= 1.1.4 already satisfied
  Verifying dependencies for vmath@2.0.0
     Info:  Dependency on x11@>= 1.1 already satisfied
  Verifying dependencies for x11@1.2
     Info:  Dependency on opengl@>= 1.2.9 already satisfied
  Verifying dependencies for opengl@1.2.9
     Info:  Dependency on x11@>= 1.1 already satisfied
  Verifying dependencies for x11@1.2
     Info:  Dependency on semver@>= 1.2.3 already satisfied
  Verifying dependencies for semver@1.2.3
 Installing lucem@2.1.2
   Building lucem/lucemd using c backend
/home/kyo/lucem/src/lucemd.nim(6, 36) Warning: imported and not used: 'pretty' [UnusedImport]
   Building lucem/lucem using c backend
/home/kyo/lucem/src/commands/run.nim(5, 35) Warning: imported and not used: 'ipinfo' [UnusedImport]
/home/kyo/lucem/src/commands/run.nim(11, 3) Warning: imported and not used: 'meta' [UnusedImport]
/home/kyo/lucem/src/commands/run.nim(11, 3) Warning: imported and not used: 'notifications' [UnusedImport]
/home/kyo/lucem/src/commands/run.nim(5, 23) Warning: imported and not used: 'thumbnails' [UnusedImport]
/home/kyo/lucem/src/commands/run.nim(8, 17) Warning: imported and not used: 'loading_screen' [UnusedImport]
/home/kyo/lucem/src/commands/run.nim(5, 16) Warning: imported and not used: 'games' [UnusedImport]
/home/kyo/lucem/src/commands/run.nim(3, 57) Warning: imported and not used: 'locks' [UnusedImport]
/home/kyo/lucem/src/commands/run.nim(3, 64) Warning: imported and not used: 'sets' [UnusedImport]
/home/kyo/lucem/src/commands/run.nim(4, 13) Warning: imported and not used: 'colored_logger' [UnusedImport]
/home/kyo/lucem/src/commands/run.nim(4, 43) Warning: imported and not used: 'pretty' [UnusedImport]
/home/kyo/lucem/src/commands/run.nim(4, 36) Warning: imported and not used: 'jsony' [UnusedImport]
/home/kyo/lucem/src/commands/explain.nim(504, 7) Warning: unreachable code after 'return' statement or '{.noReturn.}' proc [UnreachableCode]
   Building lucem/lucem_overlay using c backend
gcc: warning: Package: linker input file unused because linking not done
gcc: error: Package: linker input file not found: No such file or directory
gcc: warning: xkbcommon: linker input file unused because linking not done
gcc: error: xkbcommon: linker input file not found: No such file or directory
gcc: warning: was: linker input file unused because linking not done
gcc: error: was: linker input file not found: No such file or directory
gcc: warning: not: linker input file unused because linking not done
gcc: error: not: linker input file not found: No such file or directory
gcc: warning: found: linker input file unused because linking not done
gcc: error: found: linker input file not found: No such file or directory
gcc: warning: in: linker input file unused because linking not done
gcc: error: in: linker input file not found: No such file or directory
gcc: warning: the: linker input file unused because linking not done
gcc: error: the: linker input file not found: No such file or directory
gcc: warning: pkg-config: linker input file unused because linking not done
gcc: error: pkg-config: linker input file not found: No such file or directory
gcc: warning: search: linker input file unused because linking not done
gcc: error: search: linker input file not found: No such file or directory
gcc: warning: path.: linker input file unused because linking not done
gcc: error: path.: linker input file not found: No such file or directory
/bin/sh: -c: line 7: unexpected EOF while looking for matching `''
gcc: warning: Package: linker input file unused because linking not done
gcc: error: Package: linker input file not found: No such file or directory
gcc: warning: xkbcommon: linker input file unused because linking not done
gcc: error: xkbcommon: linker input file not found: No such file or directory
gcc: warning: was: linker input file unused because linking not done
gcc: error: was: linker input file not found: No such file or directory
gcc: warning: not: linker input file unused because linking not done
gcc: error: not: linker input file not found: No such file or directory
gcc: warning: found: linker input file unused because linking not done
gcc: error: found: linker input file not found: No such file or directory
gcc: warning: in: linker input file unused because linking not done
gcc: error: in: linker input file not found: No such file or directory
gcc: warning: the: linker input file unused because linking not done
gcc: error: the: linker input file not found: No such file or directory
gcc: warning: pkg-config: linker input file unused because linking not done
gcc: error: pkg-config: linker input file not found: No such file or directory
gcc: warning: search: linker input file unused because linking not done
gcc: error: search: linker input file not found: No such file or directory
gcc: warning: path.: linker input file unused because linking not done
gcc: error: path.: linker input file not found: No such file or directory
/bin/sh: -c: line 7: unexpected EOF while looking for matching `''
gcc: warning: Package: linker input file unused because linking not done
gcc: error: Package: linker input file not found: No such file or directory
gcc: warning: xkbcommon: linker input file unused because linking not done
gcc: error: xkbcommon: linker input file not found: No such file or directory
gcc: warning: was: linker input file unused because linking not done
gcc: error: was: linker input file not found: No such file or directory
gcc: warning: not: linker input file unused because linking not done
gcc: error: not: linker input file not found: No such file or directory
gcc: warning: found: linker input file unused because linking not done
gcc: error: found: linker input file not found: No such file or directory
gcc: warning: in: linker input file unused because linking not done
gcc: error: in: linker input file not found: No such file or directory
gcc: warning: the: linker input file unused because linking not done
gcc: error: the: linker input file not found: No such file or directory
gcc: warning: pkg-config: linker input file unused because linking not done
gcc: error: pkg-config: linker input file not found: No such file or directory
gcc: warning: search: linker input file unused because linking not done
gcc: error: search: linker input file not found: No such file or directory
gcc: warning: path.: linker input file unused because linking not done
gcc: error: path.: linker input file not found: No such file or directory
/bin/sh: -c: line 7: unexpected EOF while looking for matching `''
gcc: warning: Package: linker input file unused because linking not done
gcc: error: Package: linker input file not found: No such file or directory
gcc: warning: xkbcommon: linker input file unused because linking not done
gcc: error: xkbcommon: linker input file not found: No such file or directory
gcc: warning: was: linker input file unused because linking not done
gcc: error: was: linker input file not found: No such file or directory
gcc: warning: not: linker input file unused because linking not done
gcc: error: not: linker input file not found: No such file or directory
gcc: warning: found: linker input file unused because linking not done
gcc: error: found: linker input file not found: No such file or directory
gcc: warning: in: linker input file unused because linking not done
gcc: error: in: linker input file not found: No such file or directory
gcc: warning: the: linker input file unused because linking not done
gcc: error: the: linker input file not found: No such file or directory
gcc: warning: pkg-config: linker input file unused because linking not done
gcc: error: pkg-config: linker input file not found: No such file or directory
gcc: warning: search: linker input file unused because linking not done
gcc: error: search: linker input file not found: No such file or directory
gcc: warning: path.: linker input file unused because linking not done
gcc: error: path.: linker input file not found: No such file or directory
/bin/sh: -c: line 7: unexpected EOF while looking for matching `''
gcc: warning: Package: linker input file unused because linking not done
gcc: error: Package: linker input file not found: No such file or directory
gcc: warning: xkbcommon: linker input file unused because linking not done
gcc: error: xkbcommon: linker input file not found: No such file or directory
gcc: warning: was: linker input file unused because linking not done
gcc: error: was: linker input file not found: No such file or directory
gcc: warning: not: linker input file unused because linking not done
gcc: error: not: linker input file not found: No such file or directory
gcc: warning: found: linker input file unused because linking not done
gcc: error: found: linker input file not found: No such file or directory
gcc: warning: in: linker input file unused because linking not done
gcc: error: in: linker input file not found: No such file or directory
gcc: warning: the: linker input file unused because linking not done
gcc: error: the: linker input file not found: No such file or directory
gcc: warning: pkg-config: linker input file unused because linking not done
gcc: error: pkg-config: linker input file not found: No such file or directory
gcc: warning: search: linker input file unused because linking not done
gcc: error: search: linker input file not found: No such file or directory
gcc: warning: path.: linker input file unused because linking not done
gcc: error: path.: linker input file not found: No such file or directory
/bin/sh: -c: line 7: unexpected EOF while looking for matching `''
gcc: warning: Package: linker input file unused because linking not done
gcc: error: Package: linker input file not found: No such file or directory
gcc: warning: xkbcommon: linker input file unused because linking not done
gcc: error: xkbcommon: linker input file not found: No such file or directory
gcc: warning: was: linker input file unused because linking not done
gcc: error: was: linker input file not found: No such file or directory
gcc: warning: not: linker input file unused because linking not done
gcc: error: not: linker input file not found: No such file or directory
gcc: warning: found: linker input file unused because linking not done
gcc: error: found: linker input file not found: No such file or directory
gcc: warning: in: linker input file unused because linking not done
gcc: error: in: linker input file not found: No such file or directory
gcc: warning: the: linker input file unused because linking not done
gcc: error: the: linker input file not found: No such file or directory
gcc: warning: pkg-config: linker input file unused because linking not done
gcc: error: pkg-config: linker input file not found: No such file or directory
gcc: warning: search: linker input file unused because linking not done
gcc: error: search: linker input file not found: No such file or directory
gcc: warning: path.: linker input file unused because linking not done
gcc: error: path.: linker input file not found: No such file or directory
/bin/sh: -c: line 7: unexpected EOF while looking for matching `''
gcc: warning: Package: linker input file unused because linking not done
gcc: error: Package: linker input file not found: No such file or directory
gcc: warning: xkbcommon: linker input file unused because linking not done
gcc: error: xkbcommon: linker input file not found: No such file or directory
gcc: warning: was: linker input file unused because linking not done
gcc: error: was: linker input file not found: No such file or directory
gcc: warning: not: linker input file unused because linking not done
gcc: error: not: linker input file not found: No such file or directory
gcc: warning: found: linker input file unused because linking not done
gcc: error: found: linker input file not found: No such file or directory
gcc: warning: in: linker input file unused because linking not done
gcc: error: in: linker input file not found: No such file or directory
gcc: warning: the: linker input file unused because linking not done
gcc: error: the: linker input file not found: No such file or directory
gcc: warning: pkg-config: linker input file unused because linking not done
gcc: error: pkg-config: linker input file not found: No such file or directory
gcc: warning: search: linker input file unused because linking not done
gcc: error: search: linker input file not found: No such file or directory
gcc: warning: path.: linker input file unused because linking not done
gcc: error: path.: linker input file not found: No such file or directory
/bin/sh: -c: line 7: unexpected EOF while looking for matching `''
gcc: warning: Package: linker input file unused because linking not done
gcc: error: Package: linker input file not found: No such file or directory
gcc: warning: xkbcommon: linker input file unused because linking not done
gcc: error: xkbcommon: linker input file not found: No such file or directory
gcc: warning: was: linker input file unused because linking not done
gcc: error: was: linker input file not found: No such file or directory
gcc: warning: not: linker input file unused because linking not done
gcc: error: not: linker input file not found: No such file or directory
gcc: warning: found: linker input file unused because linking not done
gcc: error: found: linker input file not found: No such file or directory
gcc: warning: in: linker input file unused because linking not done
gcc: error: in: linker input file not found: No such file or directory
gcc: warning: the: linker input file unused because linking not done
gcc: error: the: linker input file not found: No such file or directory
gcc: warning: pkg-config: linker input file unused because linking not done
gcc: error: pkg-config: linker input file not found: No such file or directory
gcc: warning: search: linker input file unused because linking not done
gcc: error: search: linker input file not found: No such file or directory
gcc: warning: path.: linker input file unused because linking not done
gcc: error: path.: linker input file not found: No such file or directory
/bin/sh: -c: line 7: unexpected EOF while looking for matching `''
gcc: warning: Package: linker input file unused because linking not done
gcc: error: Package: linker input file not found: No such file or directory
gcc: warning: xkbcommon: linker input file unused because linking not done
gcc: error: xkbcommon: linker input file not found: No such file or directory
gcc: warning: was: linker input file unused because linking not done
gcc: error: was: linker input file not found: No such file or directory
gcc: warning: not: linker input file unused because linking not done
gcc: error: not: linker input file not found: No such file or directory
gcc: warning: found: linker input file unused because linking not done
gcc: error: found: linker input file not found: No such file or directory
gcc: warning: in: linker input file unused because linking not done
gcc: error: in: linker input file not found: No such file or directory
gcc: warning: the: linker input file unused because linking not done
gcc: error: the: linker input file not found: No such file or directory
gcc: warning: pkg-config: linker input file unused because linking not done
gcc: error: pkg-config: linker input file not found: No such file or directory
gcc: warning: search: linker input file unused because linking not done
gcc: error: search: linker input file not found: No such file or directory
gcc: warning: path.: linker input file unused because linking not done
gcc: error: path.: linker input file not found: No such file or directory
/bin/sh: -c: line 7: unexpected EOF while looking for matching `''
gcc: warning: Package: linker input file unused because linking not done
gcc: error: Package: linker input file not found: No such file or directory
gcc: warning: xkbcommon: linker input file unused because linking not done
gcc: error: xkbcommon: linker input file not found: No such file or directory
gcc: warning: was: linker input file unused because linking not done
gcc: error: was: linker input file not found: No such file or directory
gcc: warning: not: linker input file unused because linking not done
gcc: error: not: linker input file not found: No such file or directory
gcc: warning: found: linker input file unused because linking not done
gcc: error: found: linker input file not found: No such file or directory
gcc: warning: in: linker input file unused because linking not done
gcc: error: in: linker input file not found: No such file or directory
gcc: warning: the: linker input file unused because linking not done
gcc: error: the: linker input file not found: No such file or directory
gcc: warning: pkg-config: linker input file unused because linking not done
gcc: error: pkg-config: linker input file not found: No such file or directory
gcc: warning: search: linker input file unused because linking not done
gcc: error: search: linker input file not found: No such file or directory
gcc: warning: path.: linker input file unused because linking not done
gcc: error: path.: linker input file not found: No such file or directory
/bin/sh: -c: line 7: unexpected EOF while looking for matching `''
gcc: warning: Package: linker input file unused because linking not done
gcc: error: Package: linker input file not found: No such file or directory
gcc: warning: xkbcommon: linker input file unused because linking not done
gcc: error: xkbcommon: linker input file not found: No such file or directory
gcc: warning: was: linker input file unused because linking not done
gcc: error: was: linker input file not found: No such file or directory
gcc: warning: not: linker input file unused because linking not done
gcc: error: not: linker input file not found: No such file or directory
gcc: warning: found: linker input file unused because linking not done
gcc: error: found: linker input file not found: No such file or directory
gcc: warning: in: linker input file unused because linking not done
gcc: error: in: linker input file not found: No such file or directory
gcc: warning: the: linker input file unused because linking not done
gcc: error: the: linker input file not found: No such file or directory
gcc: warning: pkg-config: linker input file unused because linking not done
gcc: error: pkg-config: linker input file not found: No such file or directory
gcc: warning: search: linker input file unused because linking not done
gcc: error: search: linker input file not found: No such file or directory
gcc: warning: path.: linker input file unused because linking not done
gcc: error: path.: linker input file not found: No such file or directory
/bin/sh: -c: line 7: unexpected EOF while looking for matching `''
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3 -pthread  -I/home/kyo/.nimble/pkgs2/nanovg-0.4.0-08ff8efaeb1e09af20b11cab53ef9eb8282fc122/nanovg/deps/stb -DNANOVG_GLES3_IMPLEMENTATION Package xkbcommon was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbcommon.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xkbcommon' not found Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gl' not found -O3 -fno-strict-aliasing -fno-ident -fno-math-errno   -I/usr/lib/nim/lib -I/home/kyo/lucem/src -o /home/kyo/.cache/nim/lucem_overlay_r/@m..@s..@s.nimble@spkgs2@snanovg-0.4.0-08ff8efaeb1e09af20b11cab53ef9eb8282fc122@snanovg@ssrc@snanovg.c.o /home/kyo/.nimble/pkgs2/nanovg-0.4.0-08ff8efaeb1e09af20b11cab53ef9eb8282fc122/nanovg/src/nanovg.c' failed with exit code: 1


gcc: warning: Package: linker input file unused because linking not done
gcc: error: Package: linker input file not found: No such file or directory
gcc: warning: xkbcommon: linker input file unused because linking not done
gcc: error: xkbcommon: linker input file not found: No such file or directory
gcc: warning: was: linker input file unused because linking not done
gcc: error: was: linker input file not found: No such file or directory
gcc: warning: not: linker input file unused because linking not done
gcc: error: not: linker input file not found: No such file or directory
gcc: warning: found: linker input file unused because linking not done
gcc: error: found: linker input file not found: No such file or directory
gcc: warning: in: linker input file unused because linking not done
gcc: error: in: linker input file not found: No such file or directory
gcc: warning: the: linker input file unused because linking not done
gcc: error: the: linker input file not found: No such file or directory
gcc: warning: pkg-config: linker input file unused because linking not done
gcc: error: pkg-config: linker input file not found: No such file or directory
gcc: warning: search: linker input file unused because linking not done
gcc: error: search: linker input file not found: No such file or directory
gcc: warning: path.: linker input file unused because linking not done
gcc: error: path.: linker input file not found: No such file or directory
/bin/sh: -c: line 7: unexpected EOF while looking for matching `''
       Tip: 70 messages have been suppressed, use --verbose to show them.
nimble.nim(304)          buildFromDir

    Error:  Build failed for the package: lucem

**Comment by AshtakaOOf** [comment]
Ok I believe you will just need `libxkbcommon` a this point.

**Comment by vpuris** [comment]
tysm it worked

**Comment by AshtakaOOf** [comment]
Will have to add some more dependencies to the readme lol 😅.
